on: [push]

name: CI

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y libfuse3-dev # install fuse
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo check
